- name: Installing nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Copy Expense config file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import App from Prerequisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq

- name: Restart the Nginx service
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: true