- name: Installing MySQL Server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: enable and restart the Mysql service
  ansible.builtin.systemd_service:
    state: restarted
    name: mysqld
    enabled: true

- name: Set root Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ secrets.MYSQL_PASS }}